spring:
  application:
    name: Employee_Mangement_HRMS
  datasource:
    url: jdbc:mysql://localhost:3306/hrms
    password: Kunal@123
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      password: 123
      name: kunal
server:
  port:  9090